"""Provenance & metadata evidence (Bonus Module D): EXIF, XMP/PNG text, C2PA presence, generator markers.

Fusion policy (explicit, documented):
  * An explicit AI-generator marker in metadata is strong evidence *for* AI generation (people rarely add it by
    mistake) -> signal "supports_ai"; the combined likelihood is raised to at least 0.90.
  * Camera EXIF (make/model/exposure) is *weak* evidence for a real capture - it is trivially copied - so it
    never lowers the visual likelihood; it is reported as corroboration only.
  * Absence of metadata is neutral ("stripped") - most platform re-uploads strip it.
  * A C2PA/Content-Credentials manifest is reported (with any readable claim generator). We detect presence and
    read plain-text fields; we do NOT cryptographically validate signatures (stated limitation).
Personal data policy: GPS coordinates are never extracted - only their presence is reported.
"""
from __future__ import annotations

import re
from typing import Any

from PIL import Image
from PIL.ExifTags import TAGS

AI_MARKERS = [
    "stable diffusion", "stablediffusion", "midjourney", "dall-e", "dall·e", "dalle", "adobe firefly", "firefly",
    "imagen", "comfyui", "automatic1111", "invokeai", "novelai", "leonardo.ai", "leonardo ai", "bing image creator",
    "ideogram", "flux.1", "black forest labs", "openai", "gemini", "gpt-4o", "gpt-image", "runway", "kandinsky",
    "playground ai", "nightcafe", "dreamstudio", "sdxl", "civitai", "fooocus", "krea", "recraft", "grok", "meta ai",
    "generated by ai", "ai generated", "ai-generated", "trainedalgorithmicmedia", "digitalsourcetype",
]
AI_PNG_KEYS = {"parameters", "prompt", "workflow", "negative_prompt", "sd-metadata", "dream", "invokeai_metadata"}
EDITOR_MARKERS = ["photoshop", "lightroom", "gimp", "snapseed", "affinity", "capture one", "luminar", "canva", "picsart", "vsco"]


def _safe(v: Any) -> Any:
    if isinstance(v, bytes):
        try:
            return v.decode("utf-8", "ignore").strip("\x00")
        except Exception:  # noqa: BLE001
            return v.hex()[:64]
    if isinstance(v, (tuple, list)):
        return [_safe(x) for x in v][:16]
    if hasattr(v, "numerator"):  # IFDRational
        try:
            return float(v)
        except Exception:  # noqa: BLE001
            return str(v)
    return v


def read_exif(img: Image.Image) -> dict:
    out: dict[str, Any] = {}
    try:
        exif = img.getexif()
    except Exception:  # noqa: BLE001
        return out
    for tag_id, val in exif.items():
        name = TAGS.get(tag_id, str(tag_id))
        if name in ("GPSInfo",):
            out["gps_present"] = True  # never extract coordinates
            continue
        if name in ("MakerNote", "UserComment", "PrintImageMatching", "ExifOffset"):
            continue
        out[name] = _safe(val)
    try:
        ifd = exif.get_ifd(0x8769)  # Exif sub-IFD (exposure etc.)
        for tag_id, val in ifd.items():
            name = TAGS.get(tag_id, str(tag_id))
            if name in ("MakerNote", "UserComment"):
                continue
            out[name] = _safe(val)
        if 0x8825 in exif:
            out["gps_present"] = True
    except Exception:  # noqa: BLE001
        pass
    return out


def scan_text_markers(raw: bytes, info: dict) -> tuple[list[str], list[str], dict]:
    """Search PNG text chunks + any embedded XMP/ASCII for generator / editor markers."""
    ai_hits, editor_hits, texts = [], [], {}
    for k, v in (info or {}).items():
        if isinstance(v, (str, bytes)) and k.lower() not in ("icc_profile", "exif"):
            s = v if isinstance(v, str) else v.decode("utf-8", "ignore")
            texts[str(k)] = s[:400]
            if str(k).lower() in AI_PNG_KEYS:
                ai_hits.append(f"PNG text chunk '{k}' (generation parameters embedded)")
    head = raw[:4_000_000].decode("latin-1", "ignore").lower()
    xmp = ""
    m = re.search(r"<x:xmpmeta.*?</x:xmpmeta>", head, flags=re.S)
    if m:
        xmp = m.group(0)
        texts["xmp_excerpt"] = xmp[:600]
    for mk in AI_MARKERS:
        if mk in head:
            ai_hits.append(f"marker '{mk}' found in embedded metadata")
    for mk in EDITOR_MARKERS:
        if mk in head:
            editor_hits.append(mk)
    # dedupe preserving order
    ai_hits = list(dict.fromkeys(ai_hits))
    editor_hits = list(dict.fromkeys(editor_hits))
    return ai_hits, editor_hits, texts


def detect_c2pa(raw: bytes) -> dict:
    """Detect a C2PA / JUMBF manifest (JPEG APP11 'jumb' boxes, PNG 'caBX' chunk, or 'c2pa' labels)."""
    low = raw.lower()
    present = (b"c2pa" in low and b"jumb" in low) or b"cabx" in raw[:64] or b"caBX" in raw or b"contentauth" in low or b"c2pa.claim" in low
    claim_generator = None
    if present:
        m = re.search(rb"claim_generator[^A-Za-z0-9]{1,8}([A-Za-z0-9 ._/\-]{3,80})", raw, flags=re.I)
        if m:
            claim_generator = m.group(1).decode("latin-1", "ignore").strip()
    return {"present": bool(present), "claim_generator": claim_generator,
            "note": "Manifest presence detected; signature not cryptographically validated." if present else None}


def estimate_jpeg_quality(img: Image.Image) -> int | None:
    q = getattr(img, "quantization", None)
    if not q:
        return None
    try:
        tbl = q[0]
        mean = sum(tbl) / len(tbl)
        # rough inverse of the IJG scaling of the standard luminance table (mean ~ 58 at q50)
        if mean <= 1.05:
            return 100
        est = 100 - (mean - 1) * 50 / 57 if mean < 58 else 50 * 58 / mean
        return int(max(1, min(100, round(est))))
    except Exception:  # noqa: BLE001
        return None


def analyze_provenance(raw: bytes, img: Image.Image) -> dict:
    # Prefer the container as stored on disk: an in-memory copy (e.g. after EXIF transpose) loses format/quantization.
    if raw and getattr(img, "format", None) is None:
        try:
            import io
            img = Image.open(io.BytesIO(raw))
        except Exception:  # noqa: BLE001
            pass
    exif = read_exif(img)
    ai_hits, editor_hits, texts = scan_text_markers(raw, getattr(img, "info", {}))
    c2pa = detect_c2pa(raw)
    software = str(exif.get("Software", "") or "")
    if software:
        s = software.lower()
        if any(mk in s for mk in AI_MARKERS):
            ai_hits.insert(0, f"EXIF Software tag = '{software}'")
        elif any(mk in s for mk in EDITOR_MARKERS):
            editor_hits.insert(0, software)
    if c2pa["present"] and c2pa.get("claim_generator") and any(mk in c2pa["claim_generator"].lower() for mk in AI_MARKERS):
        ai_hits.insert(0, f"C2PA claim generator = '{c2pa['claim_generator']}'")

    camera = {k: exif.get(k) for k in ("Make", "Model", "LensModel", "ExposureTime", "FNumber", "ISOSpeedRatings", "FocalLength", "DateTimeOriginal") if exif.get(k) not in (None, "", [])}
    has_camera = bool(camera.get("Make") or camera.get("Model")) and any(k in camera for k in ("ExposureTime", "FNumber", "ISOSpeedRatings"))

    reasons: list[str] = []
    if ai_hits:
        signal = "supports_ai"
        reasons = ai_hits[:4]
    elif has_camera:
        signal = "supports_real"
        reasons = [f"camera EXIF: {camera.get('Make', '')} {camera.get('Model', '')}".strip()]
        if "ExposureTime" in camera:
            reasons.append("exposure/aperture/ISO fields present")
        if editor_hits:
            reasons.append(f"edited with {editor_hits[0]}")
    elif exif or texts or editor_hits:
        signal = "neutral"
        reasons = ["some metadata present but no camera capture data or generator marker"]
        if editor_hits:
            reasons.append(f"editing software: {editor_hits[0]}")
    else:
        signal = "stripped"
        reasons = ["no EXIF/XMP/text metadata found (typical after social-media re-upload)"]
    if c2pa["present"]:
        reasons.append("C2PA / Content Credentials manifest present" + (f" (claim generator: {c2pa['claim_generator']})" if c2pa.get("claim_generator") else ""))

    return {
        "signal": signal,
        "reasons": reasons,
        "camera": camera,
        "software": software or None,
        "editor_hits": editor_hits,
        "ai_markers": ai_hits,
        "c2pa": c2pa,
        "gps_present": bool(exif.get("gps_present", False)),
        "jpeg_quality_estimate": estimate_jpeg_quality(img),
        "format": img.format,
        "mode": img.mode,
        "exif_field_count": len(exif),
        "text_chunks": {k: v for k, v in list(texts.items())[:8]},
    }


def combine_with_visual(prob_visual: float, provenance: dict) -> dict:
    """Explicit fusion rule (see module docstring)."""
    p = prob_visual
    rule = "visual verdict only (metadata neutral or absent)"
    if provenance["signal"] == "supports_ai":
        p = max(prob_visual, 0.90)
        rule = "metadata declares AI generation -> combined likelihood raised to at least 0.90"
    elif provenance["signal"] == "supports_real":
        rule = "camera metadata corroborates but cannot lower the visual likelihood (metadata is easily copied)"
    return {"combined_probability": float(p), "rule": rule, "conflict": (provenance["signal"] == "supports_real" and prob_visual >= 0.5) or (provenance["signal"] == "supports_ai" and prob_visual < 0.5)}
